operators

1. logical =  &, |, 

2. Reginal =, >, <, !=, 

3. Additional = +, -, *, /

Strings 

*for multiline string """ cotes are used


Tuples

*are the form of list

*An order collection of elements enclosed with ()

eg = data = ('1','sushma','csd01')


List

*an order collection of elements enclosed with []

eg = data =['susush','dbdcuj','bdc', 2,1,1,2,3]


Dictionary

*unorder collection of key value pairs

eg; data = {
    'sushma' = 'name'
    '20211csd0069' = 'rollno'
}


sets

*represents the elements in the for of {}

data = {'sushma','shree',22,2323,232}



In [1]:
list = [10,20,30,40,50]
list[0]

10

In [2]:
list[0] = 100
list

[100, 20, 30, 40, 50]

In [6]:
#loopings
#while loop


i = 1
while (i<=5):
    print(i)
    i += 1

1
2
3
4
5


In [24]:
i = 0
n = 2
while(i<=5):
    print(n, "*", i, "=", n*i)
    i += 1


2 * 0 = 0
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10


In [22]:
l1 = [1,2,3,4,5]
i = 0

while i<len(l1):
    l1[i] = l1[i]+100
    i += 1
l1

[101, 102, 103, 104, 105]

In [25]:
#for loops


l1 = ['blue','red','green']

for i in l1:
    print(i)

blue
red
green


In [26]:
l1 = ['blue','red','green']
l2 = ['book','pen','bag']

for i in l1:
    for j in l2:
        print(i,j)

blue book
blue pen
blue bag
red book
red pen
red bag
green book
green pen
green bag


FUNCTION - they are the block of codewhich perform a specific task

In [2]:
def program():
    print('Hello World!')

program()

Hello World!


In [4]:
def add(x):
    return (10+x)
add(10)

20

In [6]:
def even(x):
    if x%2==0:
        print("X is even")
    else:
        print('X is not a even function')

even(10)

X is even


oop = class and objects

In [7]:
class phone:

    def make_a_call(self):
        print('Making a phone call')

    def play_game(self):
        print('Playing game')
        
p1 = phone()

In [8]:
p1.make_a_call()

Making a phone call


In [9]:
p1.play_game()

Playing game


In [20]:
class phone:
    def add_color(self,color):
        self.color = color
    
    def add_cost(self,cost):
        self.cost = cost

    def show_color(self):
        return self.color
    
    def show_cost(self):
        return self.cost
    
    def make_a_call(self):
        print('making a call')

    def play_game(self):
        print('playing a game')

In [24]:
p2 = phone()

In [25]:
p2.add_color("blue")

In [26]:
p2.add_cost(20000)

In [27]:
p2.show_color()

'blue'

In [28]:
p2.show_cost()

20000

In [1]:
# numpy

import numpy as np

In [2]:
n1 = np.array([10,20,30])
n1

array([10, 20, 30])

In [3]:
type(n1)

numpy.ndarray

In [23]:
n2 = np.array([[10,20,30],[40,50,60]])
n2
# type(n2)

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
n1 = np.zeros([10])
n1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
n1 = np.full([3,3],7)
n1

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [13]:
n1 = np.arange(1,10)
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
n1 = np.arange(100,300,50)
n1

array([100, 150, 200, 250])

In [16]:
n1 = np.random.randint(10,20,2)
n1

array([13, 10])

In [33]:
n2 = np.array([[10,20,30],[40,50,60]])
n2.shape 
n2

array([[10, 20, 30],
       [40, 50, 60]])

In [32]:
n2.shape = (3,2)
n2

array([[10, 20],
       [30, 40],
       [50, 60]])

In [40]:
a = np.array([10,20])
b = np.array([30,40])

In [41]:
a + b

array([40, 60])

to joining numpy arrays

1.vstack =  can be arranged in row 

2.jstack = can be arranged in column in a stright line

3.column_stack = can be arranged in column 

In [49]:
vs = np.array([10,20,30])
vs2 = np.array([11,22,33])
vs3 = np.array([111,222,333])
np.vstack((vs,vs2))

array([[10, 20, 30],
       [11, 22, 33]])

In [47]:
np.hstack((vs,vs2,vs3))

array([ 10,  20,  30,  11,  22,  33, 111, 222, 333])

In [48]:
np.column_stack((vs,vs2,vs3))

array([[ 10,  11, 111],
       [ 20,  22, 222],
       [ 30,  33, 333]])

pandas

data-structure = single Dimension, multi Dimension

single dimension = object series

multi dimension = Data Frame

In [1]:
import pandas as pd

In [6]:
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
type(s)
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [7]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
#2-dimensional dataFrame

from pandas import DataFrame


student = {'name':['sushma','joyce'],
         'roll_no' : ['20211csd0069','20211csd0117'],
         'marks':['100','90']}

In [13]:
pd.DataFrame(student)

name       roll_no marks
0  sushma  20211csd0069   100
1   joyce  20211csd0117    90